# --- !Ups

INSERT INTO `TIPO_DOCUMENTO` (`ID`, `NOMBRE_TIPO`,`FLAG1`,`FLAG2`, `FECHA_CREACION`, `FECHA_MODIFICACION`) values ('12345','OFICIO CIRCULAR','0','0',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO `TIPO_DOCUMENTO` (`ID`, `NOMBRE_TIPO`,`FLAG1`,`FLAG2`, `FECHA_CREACION`, `FECHA_MODIFICACION`) values ('67891','PROVEIDO','0','0',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO `TIPO_DOCUMENTO` (`ID`, `NOMBRE_TIPO`,`FLAG1`,`FLAG2`, `FECHA_CREACION`, `FECHA_MODIFICACION`) values ('35845','OFICIO','0','0',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);