# --- !Ups

INSERT INTO `TIPO_DOCUMENTO` (`ID`, `NOMBRE_TIPO`,`FLAG1`,`FLAG2`, `FECHA_CREACION`, `FECHA_MODIFICACION`) values ('14545','EXPEDIENTE','0','P',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO `TIPO_DOCUMENTO` (`ID`, `NOMBRE_TIPO`,`FLAG1`,`FLAG2`, `FECHA_CREACION`, `FECHA_MODIFICACION`) values ('24545','HOJA DE REQUERIMIENTO','3','NP',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO `TIPO_DOCUMENTO` (`ID`, `NOMBRE_TIPO`,`FLAG1`,`FLAG2`, `FECHA_CREACION`, `FECHA_MODIFICACION`) values ('34545','INFORME','0','P',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO `TIPO_DOCUMENTO` (`ID`, `NOMBRE_TIPO`,`FLAG1`,`FLAG2`, `FECHA_CREACION`, `FECHA_MODIFICACION`) values ('44545','OFICIO','0','P',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO `TIPO_DOCUMENTO` (`ID`, `NOMBRE_TIPO`,`FLAG1`,`FLAG2`, `FECHA_CREACION`, `FECHA_MODIFICACION`) values ('54545','OFICIO CIRCULAR','0','NPC',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO `TIPO_DOCUMENTO` (`ID`, `NOMBRE_TIPO`,`FLAG1`,`FLAG2`, `FECHA_CREACION`, `FECHA_MODIFICACION`) values ('64545','CARTA','0','P',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO `TIPO_DOCUMENTO` (`ID`, `NOMBRE_TIPO`,`FLAG1`,`FLAG2`, `FECHA_CREACION`, `FECHA_MODIFICACION`) values ('74545','INFORME CIRCULAR','0','NPC',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO `TIPO_DOCUMENTO` (`ID`, `NOMBRE_TIPO`,`FLAG1`,`FLAG2`, `FECHA_CREACION`, `FECHA_MODIFICACION`) values ('84545','PROVEIDOS','2','NP',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO `TIPO_DOCUMENTO` (`ID`, `NOMBRE_TIPO`,`FLAG1`,`FLAG2`, `FECHA_CREACION`, `FECHA_MODIFICACION`) values ('94545','MEMORANDUM','0','P',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO `TIPO_DOCUMENTO` (`ID`, `NOMBRE_TIPO`,`FLAG1`,`FLAG2`, `FECHA_CREACION`, `FECHA_MODIFICACION`) values ('114545','DIRECTIVAS','0','P',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO `TIPO_DOCUMENTO` (`ID`, `NOMBRE_TIPO`,`FLAG1`,`FLAG2`, `FECHA_CREACION`, `FECHA_MODIFICACION`) values ('224545','ARCHIVO','0','NP',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO `TIPO_DOCUMENTO` (`ID`, `NOMBRE_TIPO`,`FLAG1`,`FLAG2`, `FECHA_CREACION`, `FECHA_MODIFICACION`) values ('334545','REPORTE','0','P',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);